[env.production]
name = "dlls-app"
workers_dev = true

[site]
bucket = ".next"
entry-point = "."

[build]
command = "npm install && npm run build"
watch_dir = "build/worker"
pages_build_output_dir = ".next"

[build.upload]
format = "modules"
main = "./worker.mjs"

[build.environment]
NODE_VERSION = "18.20.8" 