[env.production]
name = "dlls-app"
workers_dev = true

[site]
bucket = ".vercel/output/static"
entry-point = ".vercel/output/functions/middleware"

[build]
command = "npm run build"
watch_dir = "build/worker"

[build.upload]
format = "modules"
main = "./worker.mjs" 